---
title: "HW1"
author: "Hongfeng Jiang (hj2443)"
date: "Feb,1st,2017"
output:
  html_document: default
  pdf_document: default
---

Prob 2.1
```{r,warning=FALSE}
library(leaps)
credit<-read.csv("Credit.csv")
credit<-credit[,-1]
best<-regsubsets(Balance~.,data=credit,nvmax=11)
forwardstep<-regsubsets(Balance~.,data=credit,method = "forward",nvmax=11)
backwardstep<-regsubsets(Balance~.,data=credit,method = "backward",nvmax=11)
plot(c(0:11),best$rss,col="red",type = "b",ylab="Residual sum-of-squares", xlab="Number of variables")
lines(c(0:11),forwardstep$rss,col="blue",type="b",lty=2)
lines(c(0:11),backwardstep$rss,col="green",type="b",lty=3)
legend("topright",legend = c("best","forwardstep","backwardstep"), col= c("red","blue","green"),lty=1:3)
```

2.2
```{r}
best_sum<-summary(best)
forwardstep_sum<-summary(forwardstep)
backwardstep_sum<-summary(backwardstep)
#for best subset selection
which.min(best_sum$cp)
which.min(best_sum$bic)
#for forward stepwise selection
which.min(forwardstep_sum$cp)
which.min(forwardstep_sum$bic)
#for backward stepwise selection
which.min(backwardstep_sum$cp)
which.min(backwardstep_sum$bic)
```

3.1
```{r}
dict<-list()
symbols<-read.csv("dow.csv",header = F)
company<-symbols[,1]
filenames<-paste("http://ichart.finance.yahoo.com/table.csv?s=",company,"&a=00&b=1&c=2010&d=00&e=1&f=2011&g=d&ignore=.csv")
dict<-lapply(filenames, read.csv, header = TRUE)
names(dict)<-company
transp<-function(df){
  df<-df[,"Close"]
  return(df)
}
dict<-lapply(dict,transp)
stockprice<-do.call(cbind,dict)
```

3.2
```{r}
pc_stock<-princomp(stockprice)
biplot(pc_stock)
screeplot(pc_stock,type = "lines")
```

3.3
```{r}
pc_stock_cor<-princomp(stockprice,cor = T)
biplot(pc_stock_cor)
screeplot(pc_stock_cor,type="lines")
```

3.4
```{r}
re<-matrix(NA,nrow =nrow(stockprice)-1,ncol=ncol(stockprice))
for (i in 1:nrow(stockprice)-1){
  re[i,]<-((stockprice[i+1,]-stockprice[i,])/stockprice[i+1,])
}
pc_return_cor<-princomp(re,cor=T)
biplot(pc_return_cor)
screeplot(pc_return_cor,type = "lines")
```
